name = "interns-ticket-manager"
main = "worker/index.js"
compatibility_date = "2026-06-26"

[vars]
ADMIN_USER_ID = "U0B9YUFNMJB"
GITHUB_REPO = "masonite-byte/interns-ticket-manager"
SLACK_CHANNEL_ID = "C0BACATB8BY"

[[kv_namespaces]]
binding = "TICKET_STORE"
id = "f3808d3f2a8146059a9447c9df09ff85"

[triggers]
crons = ["0 9 * * 1-5"]
